version: '3'

services:
  web:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./app:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - php
      - db
    restart: always

  php:
    image: php:7.4-fpm
    container_name: php-fpm
    volumes:
      - ./app:/var/www/html
    restart: always

  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: app_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always

